version: "3.5"
services:
  pinterest_backend:
    build: ./backend
    image: pinterest_backend
    env_file: .env
    # volumes:
    #   - ./backend/:/backend/
    expose: 
      - 8000
    restart: always
    environment:
      - PORT=8000

  pinterest_frontend:
    build: ./frontend
    # command: npm run start
    # env_file: .env
    # volumes:
    #   - ./frontend/:/frontend/
    expose:
      - 3000
    environment:
      - PORT=3000

  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports: 
      - 80:80
      - 443:443
      - 2019:2019

  redis:
    image: redis:alpine
    expose:
      - 6379
